// CLIENT MOTIVE POOL — engine-dealt, one per card, seeded.
//
// Designer 2026-08-24: "your fix for monotony is to force tropes? i'm okay with that as long as
// it's seeded (generate 100+ list and pick one at random)."
//
// Grounding: the reference individuates a job by the CLIENT'S MOTIVE, never by the craft — Jenna's
// fourteen commissions are all "make jewellery" and differ only in why the client wants it (a vain
// lord wants the stone to look large; a woman about to give birth wants a blessing; a palace eunuch
// needs slaves to wear something worthy of the Sultan's house). That maps onto our "escort a
// caravan x40" problem. See prosebench/TRANSFER.md.
//
// SHAPE WARNING (measured law): prose-shaped fields get pasted verbatim — it happened with the pay
// envelope and again with an oddActor rotation. These are deliberately written as a WANT and a
// CONCEALMENT, terse and unquotable, so the writer has to render them rather than copy them.
// 120 entries: at one per card a given motive recurs about once per 120 cards.

export interface Motive { want: string; hides: string }

export const MOTIVES: Motive[] = [
  { want: 'looks generous', hides: 'is paying off a blackmailer' },
  { want: 'the thing back', hides: 'never owned it' },
  { want: 'a witness gone', hides: 'calls it a rescue' },
  { want: 'his name cleared', hides: 'did it' },
  { want: 'a debt cancelled', hides: 'the debt is to him' },
  { want: 'the body found', hides: 'wants it not found' },
  { want: 'a rival embarrassed', hides: 'says it is about safety' },
  { want: 'the road open', hides: 'owns the only other road' },
  { want: 'his son back', hides: 'the boy ran on purpose' },
  { want: 'the beast killed', hides: 'has been feeding it' },
  { want: 'proof of a death', hides: 'to remarry' },
  { want: 'a shrine restored', hides: 'to look devout before a trial' },
  { want: 'the well cleared', hides: 'put something in it' },
  { want: 'a daughter recovered', hides: 'sold her' },
  { want: 'papers retrieved', hides: 'they name him' },
  { want: 'a tenant removed', hides: 'the tenant has the older claim' },
  { want: 'the herd counted', hides: 'is short and knows why' },
  { want: 'an heirloom valued', hides: 'means to sell it before the reading of a will' },
  { want: 'a wall rebuilt', hides: 'it fell because he skimped' },
  { want: 'the thief caught', hides: 'the thief is family' },
  { want: 'an escort north', hides: 'is fleeing, not travelling' },
  { want: 'the mill running', hides: 'has no right to it' },
  { want: 'a grave opened', hides: 'buried something with the body' },
  { want: 'the dogs put down', hides: 'set them loose himself' },
  { want: 'a letter delivered', hides: 'has not read it and is afraid to' },
  { want: 'the ford watched', hides: 'expects someone to come back' },
  { want: 'a stranger driven off', hides: 'the stranger is owed money' },
  { want: 'the fire explained', hides: 'was seen nearby' },
  { want: 'her husband found', hides: 'hopes he is dead' },
  { want: 'a boundary settled', hides: 'moved the stone' },
  { want: 'the crop saved', hides: 'already sold it twice' },
  { want: 'an apprentice returned', hides: 'beat him' },
  { want: 'the ledger recovered', hides: 'to burn it' },
  { want: 'a wolf tracked', hides: 'it is not a wolf' },
  { want: 'the bridge guarded', hides: 'means to collect the toll himself' },
  { want: 'his brother warned', hides: 'they have not spoken in years' },
  { want: 'the ruin surveyed', hides: 'has already looted it' },
  { want: 'a horse recovered', hides: 'lost it at dice' },
  { want: 'the priest escorted', hides: 'the priest is under guard, not protection' },
  { want: 'a rumour stopped', hides: 'the rumour is true' },
  { want: 'the ice cut', hides: 'needs the pond empty before the thaw' },
  { want: 'a child found', hides: 'is not the parent' },
  { want: 'the toll collected', hides: 'the right lapsed a year ago' },
  { want: 'a beast taken alive', hides: 'means to set it on someone' },
  { want: 'the sick tended', hides: 'wants the house cleared' },
  { want: 'a map copied', hides: 'the original is stolen' },
  { want: 'the flock moved', hides: 'the pasture is not his' },
  { want: 'her sister fetched', hides: 'the sister does not want fetching' },
  { want: 'a shipment met', hides: 'it is not what the papers say' },
  { want: 'the tower watched', hides: 'is waiting for a signal' },
  { want: 'a hedge cleared', hides: 'to see into a neighbour\'s yard' },
  { want: 'an oath witnessed', hides: 'intends to break it' },
  { want: 'the cellar opened', hides: 'sealed it himself' },
  { want: 'a rider caught', hides: 'the rider carries his confession' },
  { want: 'the harvest guarded', hides: 'has promised it to two buyers' },
  { want: 'a name confirmed', hides: 'hopes it is the wrong one' },
  { want: 'the pit filled', hides: 'someone is in it' },
  { want: 'a debt collected', hides: 'the debtor paid already' },
  { want: 'her son taught a trade', hides: 'wants him away from the house' },
  { want: 'the reeds burned', hides: 'to drive out a squatter' },
  { want: 'a fence mended', hides: 'the cattle were driven off, not strayed' },
  { want: 'the tax roll read', hides: 'cannot read' },
  { want: 'a dowry escorted', hides: 'it is short' },
  { want: 'the corpse identified', hides: 'already knows' },
  { want: 'a room searched', hides: 'to plant something' },
  { want: 'the hunt led', hides: 'wants a rival to fall behind' },
  { want: 'his wife followed', hides: 'she is meeting a creditor, not a lover' },
  { want: 'the mine reopened', hides: 'it was closed for a reason' },
  { want: 'a horse broken', hides: 'it threw and killed a man' },
  { want: 'the boundary walked', hides: 'to find where a body was left' },
  { want: 'a signal answered', hides: 'nobody sent it' },
  { want: 'the granary counted', hides: 'to know what can be hidden' },
  { want: 'a stranger vouched for', hides: 'has never met him' },
  { want: 'the sheep found', hides: 'ate them' },
  { want: 'a chest carried', hides: 'will not say what is in it' },
  { want: 'the churchyard watched', hides: 'expects it to be robbed by his own man' },
  { want: 'a witness escorted', hides: 'to a place they will not leave' },
  { want: 'the road cleared of beggars', hides: 'one of them is his father' },
  { want: 'a tree felled', hides: 'it marks a grave' },
  { want: 'the deed found', hides: 'to destroy it' },
  { want: 'a fight stopped', hides: 'started it' },
  { want: 'the goods valued', hides: 'they are stolen and he knows' },
  { want: 'a girl married off', hides: 'she is already promised elsewhere' },
  { want: 'the marsh drained', hides: 'what is under it' },
  { want: 'a captive ransomed', hides: 'took the ransom already' },
  { want: 'the roof mended', hides: 'to stop an inspection' },
  { want: 'a beast identified', hides: 'wants it declared a devil, not a dog' },
  { want: 'the crossing forced', hides: 'is late to a hanging he must attend' },
  { want: 'a stolen ring found', hides: 'gave it away drunk' },
  { want: 'the miller questioned', hides: 'owes the miller money' },
  { want: 'a plot guarded', hides: 'to keep others from digging' },
  { want: 'the pilgrims counted', hides: 'is paid by the head' },
  { want: 'a bell recast', hides: 'the old one bears the wrong name' },
  { want: 'the borders watched', hides: 'to know when to run' },
  { want: 'a runaway returned', hides: 'the runaway is owed wages' },
  { want: 'the smoke explained', hides: 'lit it' },
  { want: 'a grave moved', hides: 'the land is being sold' },
  { want: 'the hound found', hides: 'it bit a child and he hid it' },
  { want: 'a wagon escorted', hides: 'it is empty and meant to be robbed' },
  { want: 'the widow visited', hides: 'to press a claim before the funeral' },
  { want: 'a cellar stocked', hides: 'for people, not goods' },
  { want: 'the boundary stones read', hides: 'cannot read them either' },
  { want: 'a bird recovered', hides: 'it carried a message' },
  { want: 'the pond netted', hides: 'to find what was thrown in' },
  { want: 'a debtor found', hides: 'means to kill him, not collect' },
  { want: 'the road mended', hides: 'a cart of his went off it' },
  { want: 'a house watched', hides: 'is not welcome there' },
  { want: 'the strangers fed', hides: 'to keep them where he can see them' },
  { want: 'a shrine emptied', hides: 'the offerings are his rent' },
  { want: 'the boy apprenticed', hides: 'the boy saw something' },
  { want: 'a lock opened', hides: 'the key is with someone he wronged' },
  { want: 'the beasts penned', hides: 'they are not his to pen' },
  { want: 'a fen crossed', hides: 'has crossed it before and lost men' },
  { want: 'the drowned recovered', hides: 'pushed him' },
  { want: "a stranger's story checked", hides: 'the story is his own, told back' },
  { want: 'the fields blessed', hides: 'salted them himself' },
  { want: 'a wall breached', hides: 'to prove it can be' },
  { want: 'the old road found', hides: 'to move goods off the toll road' },
  { want: 'a lamp kept lit', hides: 'is afraid of what the dark brings' },
  { want: 'the pack recovered', hides: 'the contents are not his' },
];
