// CLIENT MOTIVE POOL v2 — the `hides` field reshaped as an OBSERVABLE TELL.
//
// v1 dealt the client's inner motive ("is paying off a blackmailer"). The model pasted it as an
// explanation — "though the money is to buy off a blackmailer" — in 46% of cards, because a
// psychological truth can only enter prose AS a statement of that truth.
// v2 deals a THING THAT CAN BE SEEN instead. Pasting an observable detail is harmless: it IS the
// card's concrete particular. This is the same principle as the engine's pay glosses being
// "pre-shaped to read whole if pasted" (game.ts:907) — make the field safe to copy rather than
// forbidding the copy.
export interface Motive2 { want: string; tell: string }
export const MOTIVES2: Motive2[] = [
  { want: 'the ruin cleared, and to be seen paying for it', tell: 'he counts the fee out twice and still gets it wrong' },
  { want: 'his horse back', tell: 'the saddle is already gone, sold separately' },
  { want: 'a chest carried inland', tell: 'it is roped shut in three places and none of the knots match' },
  { want: 'the beasts penned', tell: 'the brands on them have been cut out' },
  { want: 'her husband found', tell: 'she has already moved his tools out of the shed' },
  { want: 'the hunt led out at dawn', tell: 'he has told two different men they will lead it' },
  { want: 'a bird brought back alive', tell: 'there is a thread still tied to its leg' },
  { want: 'the thief caught', tell: 'he asks that the thief not be brought through the village' },
  { want: 'the pit filled before the rains', tell: 'the spoil heap beside it is smaller than the hole' },
  { want: 'the ridgeline watched', tell: 'his cart is loaded and standing in the yard' },
  { want: 'proof her husband is dead', tell: 'the banns are already read' },
  { want: 'her sister fetched home', tell: 'the sister sent back the money that was sent to her' },
  { want: 'the well cleared', tell: 'he will not draw from it himself while you work' },
  { want: 'a debt collected', tell: 'the account he shows you is written in one hand, start to finish' },
  { want: 'the boy returned to his apprenticeship', tell: 'the boy left his good boots behind' },
  { want: 'a grave opened', tell: 'he brings his own spade and will not lend it' },
  { want: 'the dogs put down', tell: 'they come to him when he calls them' },
  { want: 'a letter delivered upriver', tell: 'the seal on it is fresh but the paper is old' },
  { want: 'the ford watched for a week', tell: 'he asks what time the watch changes' },
  { want: 'a stranger driven off his land', tell: 'the stranger has been there longer than he has' },
  { want: 'the fire explained', tell: 'he was in the next village that night and can name who saw him' },
  { want: 'a boundary settled', tell: 'the stone has been moved recently — the grass under it is still green' },
  { want: 'the crop got in fast', tell: 'two different factors have receipts for it' },
  { want: 'an account book recovered', tell: 'he asks for it unopened, and says so twice' },
  { want: 'the wolf tracked', tell: 'the sheep were killed but not eaten' },
  { want: 'the bridge guarded', tell: 'he has already had a toll-board painted' },
  { want: 'the ruin surveyed', tell: 'he knows how many rooms it has' },
  { want: 'a rumour stopped', tell: 'he repeats it to you in full, twice, to be sure you have it right' },
  { want: 'a child found', tell: 'he does not know what colour her hair is' },
  { want: 'the sick tended at his own cost', tell: 'he has had their beds moved to the outbuilding already' },
  { want: 'a map copied', tell: 'the original has another man\'s name scratched off the corner' },
  { want: 'the flock moved to new pasture', tell: 'the new pasture is on the far side of a border' },
  { want: 'a shipment met at the landing', tell: 'the manifest is lighter than the cart will be' },
  { want: 'the cellar opened', tell: 'the lock is new and the door is old' },
  { want: 'a rider caught before the crossing', tell: 'he cannot say what the rider carries, only that it must not arrive' },
  { want: 'the harvest guarded', tell: 'he has hired three separate parties to guard it' },
  { want: 'a corpse identified', tell: 'he brings the dead man\'s ring with him' },
  { want: 'a room searched', tell: 'he tells you which board to look under' },
  { want: 'the mine reopened', tell: 'the last crew\'s tools are still down there' },
  { want: 'a horse broken to saddle', tell: 'nobody local will bid on it' },
  { want: 'the granary counted', tell: 'he asks for the count in writing, and for no copy to be kept' },
  { want: 'a stranger vouched for', tell: 'they arrived on the same day' },
  { want: 'the churchyard watched', tell: 'his own man has the other key' },
  { want: 'a tree felled at the field\'s corner', tell: 'the ground around it is bare where nothing has been planted' },
  { want: 'a deed found', tell: 'he describes the box it is in before you ask' },
  { want: 'a fight stopped at the mill', tell: 'both men work for him' },
  { want: 'goods valued honestly', tell: 'the crates are packed in straw from another county' },
  { want: 'the marsh drained', tell: 'he asks for the spoil carted away, not spread' },
  { want: 'a captive ransomed', tell: 'the ransom he offers is under what the family already paid' },
  { want: 'a runaway returned', tell: 'her wages are still owed and he mentions them first' },
  { want: 'the smoke on the ridge explained', tell: 'he smelled of it when he arrived' },
  { want: 'a grave moved before the sale', tell: 'the buyer is waiting in his yard' },
  { want: 'the hound found', tell: 'he asks whether it can be brought back muzzled' },
  { want: 'a wagon escorted to market', tell: 'it rides high for a full load' },
  { want: 'the widow visited before the funeral', tell: 'he has a paper for her to mark' },
  { want: 'a lock opened without the key', tell: 'the key is with a man he will not name' },
  { want: 'the drowned man recovered', tell: 'he knows which bend to look in' },
  { want: 'the fields blessed', tell: 'nothing has grown in the near strip for two seasons' },
  { want: 'the old road found again', tell: 'he asks whether the man on the toll gate can see it' },
  { want: 'a lamp kept burning at the crossing', tell: 'he pays for a month at once and gives no name' },

  // ── expansion to production size (designer: pool should be 150+ so a tell recurs about once
  // per 150 draws rather than once per 60)
  { want: 'a boat pulled off the mud', tell: 'the oars are already stowed in his own shed' },
  { want: 'the pigs found', tell: 'he has cleaned the sty out ready' },
  { want: 'her son talked sense into', tell: 'she asks that nobody speak to him alone' },
  { want: 'a wall walked and measured', tell: 'he paces it out for you before you agree' },
  { want: 'the miller paid off', tell: "the sacks in his yard bear the miller's mark" },
  { want: 'a cart mended by market day', tell: 'the axle was cut, not worn through' },
  { want: 'the strangers moved on', tell: 'he has fed them every night for a week' },
  { want: 'a ring found in the rushes', tell: 'he describes the inside of the band' },
  { want: 'the roof watched at night', tell: 'there is new thatch on one side only' },
  { want: 'a bull brought back', tell: 'the gate was lifted off its hinges, not broken' },
  { want: 'the reeve spoken to quietly', tell: 'he asks you to go after dark' },
  { want: 'a boy kept out of the mine', tell: "the boy's father is not mentioned once" },
  { want: 'her dowry recovered', tell: 'the chest it came in is still in her room' },
  { want: 'the orchard guarded', tell: 'the windfalls have been swept up already' },
  { want: 'a wound looked at', tell: 'he keeps his sleeve down while he talks' },
  { want: 'the dam checked', tell: 'he asks that it be checked from the far bank only' },
  { want: 'a name kept off a list', tell: 'he has the list with him' },
  { want: 'the ferry run for a week', tell: "the ferryman's dog is at his heel" },
  { want: 'a hive moved before winter', tell: 'the bees are already dead' },
  { want: 'the corn measured', tell: 'he brings his own measure' },
  { want: 'a horse shod quietly', tell: 'there is a brand under the new shoe' },
  { want: 'the ditch dug deeper', tell: 'the old ditch was dug last month' },
  { want: 'her brother watched', tell: 'she pays more than the work is worth' },
  { want: 'a fire kept lit at the ford', tell: 'he asks for it lit at the same hour each night' },
  { want: 'the barrels counted', tell: 'two are lighter than the rest and he knows which' },
  { want: 'a message carried and no answer waited for', tell: 'he does not ask what happens after' },
  { want: 'the sheep dipped', tell: 'the flock is bigger than his pasture holds' },
  { want: "a stranger's boots returned", tell: 'the boots are the wrong size for the man he names' },
  { want: 'the smith kept busy', tell: 'he pays for a week of work with nothing to make' },
  { want: 'a well capped', tell: 'the rope has been cut off short' },
  { want: 'the pond drained by spring', tell: 'he asks who will be watching while it drains' },
  { want: 'a door hung on a ruin', tell: 'the ruin has no roof' },
  { want: 'her cat found', tell: 'she has already had the yard dug over' },
  { want: 'the tolls counted for a day', tell: 'he stands where he cannot see the road' },
  { want: 'a coffin carried at night', tell: 'it is lighter than a man' },
  { want: 'the geese driven to market', tell: 'the market is three days the other way' },
  { want: 'a debt written off', tell: 'the notched stick has been snapped and rejoined' },
  { want: 'the road watched for a rider', tell: 'he has a horse saddled in the yard' },
  { want: "a child's grave tidied", tell: 'there is no name on the stone' },
  { want: 'the barn cleared out', tell: 'he will not go inside with you' },
  { want: 'a lock changed', tell: 'the old key is on the table between you' },
  { want: 'the sheep counted at dusk', tell: 'he asks the count be given to him alone' },
  { want: 'a stranger followed home', tell: 'he already knows which lane' },
  { want: 'the ice broken on the pond', tell: 'he asks what floats up' },
  { want: 'a will witnessed', tell: 'the man who is to sign it is not present' },
  { want: 'the hedge laid before spring', tell: 'it has been laid twice this year' },
  { want: 'a lamp carried to the barrow', tell: 'he stops at the field gate and waits' },
  { want: 'the horses moved after dark', tell: 'their hooves have been wrapped' },
  { want: 'a stall watched at market', tell: 'the goods on it are not from here' },
  { want: 'the bell rung at midnight', tell: 'he asks that it be rung only once' },
  { want: 'a cellar counted for rats', tell: 'the traps in it are unset' },
  { want: 'the crossing kept clear', tell: 'he asks how long a man could hide under the bridge' },
  { want: "a stranger's horse stabled", tell: 'the saddlebags are gone from it' },
  { want: 'the ford staked out', tell: 'the stakes are already cut and stacked' },
  { want: 'a bundle burned unopened', tell: 'the string on it is his own' },
  { want: 'the pigs kept off the common', tell: 'the common is not his to keep them off' },
  { want: 'a man walked home safe', tell: 'he asks which way you will take him' },
  { want: 'the shutters nailed', tell: 'from the inside' },
  { want: 'a debt read aloud in the square', tell: 'he cannot read it himself' },
  { want: 'the calves marked', tell: 'the marking iron is new' },
  { want: 'a body carried to the church', tell: 'he has already paid the sexton' },
  { want: 'the meadow mown early', tell: 'it is not ready and he knows it' },
  { want: 'a strongbox moved', tell: 'he asks that it be moved during the fair' },
  { want: 'the woodpile searched', tell: 'he says which end to start' },
  { want: 'a letter burned after reading', tell: 'he watches to see you read it' },
  { want: 'the herd driven at night', tell: 'the drove road runs past a gate he owns' },
  { want: 'a hole in a wall mended', tell: 'the stones from it are stacked neatly nearby' },
  { want: 'the tanner questioned', tell: 'he owes the tanner nothing, he says twice' },
  { want: 'a girl escorted to her wedding', tell: 'she has not been told' },
  { want: 'the culvert cleared', tell: 'there is cloth caught in the grating' },
  { want: "a stranger's tools returned", tell: 'the tools have his own mark filed off' },
  { want: 'the mill wheel stopped for a day', tell: 'the miller was not asked' },
  { want: 'a grave watched three nights', tell: 'he names the third night first' },
  { want: 'the fence line walked', tell: 'he walks it with you but not to the end' },
  { want: 'a sack weighed', tell: 'the scales are his' },
  { want: 'the bees smoked out', tell: 'he has bought the hives already' },
  { want: 'a boat watched at the landing', tell: 'it has been unloaded once tonight' },
  { want: 'the well water tasted', tell: 'he will not drink it in front of you' },
  { want: "a stranger's story taken down", tell: 'he supplies the dates before the man does' },
  { want: 'the loft cleared', tell: 'the ladder has been moved away from it' },
  { want: 'a hound kept from the hunt', tell: 'the hound belongs to someone else' },
  { want: 'the millpond netted', tell: 'he asks for anything found to be brought to him whole' },
  { want: 'a lantern left on the ridge', tell: 'he asks that it be left unlit' },
  { want: 'the causeway watched at low tide', tell: 'he knows exactly when that is' },
  { want: 'a barn door held shut', tell: 'from the outside' },
  { want: 'the flock brought down early', tell: 'the high pasture has been burned' },
  { want: 'a ring melted down', tell: 'it is still warm' },
  { want: 'the rick counted', tell: 'he built it himself, alone, in one night' },
  { want: 'a stranger buried decently', tell: 'he supplies the shroud' },
];
