// CLIENT MOTIVE POOL v2 — the `hides` field reshaped as an OBSERVABLE TELL.
//
// v1 dealt the client's inner motive ("is paying off a blackmailer"). The model pasted it as an
// explanation — "though the money is to buy off a blackmailer" — in 46% of cards, because a
// psychological truth can only enter prose AS a statement of that truth.
// v2 deals a THING THAT CAN BE SEEN instead. Pasting an observable detail is harmless: it IS the
// card's concrete particular. This is the same principle as the engine's pay glosses being
// "pre-shaped to read whole if pasted" (game.ts:907) — make the field safe to copy rather than
// forbidding the copy.
export interface Motive2 { want: string; tell: string }
export const MOTIVES2: Motive2[] = [
  { want: 'the ruin cleared, and to be seen paying for it', tell: 'he counts the fee out twice and still gets it wrong' },
  { want: 'his horse back', tell: 'the saddle is already gone, sold separately' },
  { want: 'a chest carried inland', tell: 'it is roped shut in three places and none of the knots match' },
  { want: 'the beasts penned', tell: 'the brands on them have been cut out' },
  { want: 'her husband found', tell: 'she has already moved his tools out of the shed' },
  { want: 'the hunt led out at dawn', tell: 'he has told two different men they will lead it' },
  { want: 'a bird brought back alive', tell: 'there is a thread still tied to its leg' },
  { want: 'the thief caught', tell: 'he asks that the thief not be brought through the village' },
  { want: 'the pit filled before the rains', tell: 'the spoil heap beside it is smaller than the hole' },
  { want: 'the ridgeline watched', tell: 'his cart is loaded and standing in the yard' },
  { want: 'proof her husband is dead', tell: 'the banns are already read' },
  { want: 'her sister fetched home', tell: 'the sister sent back the money that was sent to her' },
  { want: 'the well cleared', tell: 'he will not draw from it himself while you work' },
  { want: 'a debt collected', tell: 'the tally he shows you is written in one hand, start to finish' },
  { want: 'the boy returned to his apprenticeship', tell: 'the boy left his good boots behind' },
  { want: 'a grave opened', tell: 'he brings his own spade and will not lend it' },
  { want: 'the dogs put down', tell: 'they come to him when he calls them' },
  { want: 'a letter delivered upriver', tell: 'the seal on it is fresh but the paper is old' },
  { want: 'the ford watched for a week', tell: 'he asks what time the watch changes' },
  { want: 'a stranger driven off his land', tell: 'the stranger has been there longer than he has' },
  { want: 'the fire explained', tell: 'he was in the next village that night and can name who saw him' },
  { want: 'a boundary settled', tell: 'the stone has been moved recently — the grass under it is still green' },
  { want: 'the crop got in fast', tell: 'two different factors have receipts for it' },
  { want: 'a ledger recovered', tell: 'he wants it brought to him unopened, and says so twice' },
  { want: 'the wolf tracked', tell: 'the sheep were killed but not eaten' },
  { want: 'the bridge guarded', tell: 'he has already had a toll-board painted' },
  { want: 'the ruin surveyed', tell: 'he knows how many rooms it has' },
  { want: 'a rumour stopped', tell: 'he repeats it to you in full, twice, to be sure you have it right' },
  { want: 'a child found', tell: 'he does not know what colour her hair is' },
  { want: 'the sick tended at his own cost', tell: 'he has had their beds moved to the outbuilding already' },
  { want: 'a map copied', tell: 'the original has another man\'s name scratched off the corner' },
  { want: 'the flock moved to new pasture', tell: 'the new pasture is on the far side of a border' },
  { want: 'a shipment met at the landing', tell: 'the manifest is lighter than the cart will be' },
  { want: 'the cellar opened', tell: 'the lock is new and the door is old' },
  { want: 'a rider caught before the crossing', tell: 'he cannot say what the rider carries, only that it must not arrive' },
  { want: 'the harvest guarded', tell: 'he has hired three separate parties to guard it' },
  { want: 'a corpse identified', tell: 'he brings the dead man\'s ring with him' },
  { want: 'a room searched', tell: 'he tells you which board to look under' },
  { want: 'the mine reopened', tell: 'the last crew\'s tools are still down there' },
  { want: 'a horse broken to saddle', tell: 'nobody local will bid on it' },
  { want: 'the granary counted', tell: 'he asks for the count in writing, and for no copy to be kept' },
  { want: 'a stranger vouched for', tell: 'they arrived on the same day' },
  { want: 'the churchyard watched', tell: 'his own man has the other key' },
  { want: 'a tree felled at the field\'s corner', tell: 'the ground around it is bare where nothing has been planted' },
  { want: 'a deed found', tell: 'he describes the box it is in before you ask' },
  { want: 'a fight stopped at the mill', tell: 'both men work for him' },
  { want: 'goods valued honestly', tell: 'the crates are packed in straw from another county' },
  { want: 'the marsh drained', tell: 'he wants the spoil carted away, not spread' },
  { want: 'a captive ransomed', tell: 'the ransom he offers is under what the family already paid' },
  { want: 'a runaway returned', tell: 'her wages are still owed and he mentions them first' },
  { want: 'the smoke on the ridge explained', tell: 'he smelled of it when he arrived' },
  { want: 'a grave moved before the sale', tell: 'the buyer is waiting in his yard' },
  { want: 'the hound found', tell: 'he asks whether it can be brought back muzzled' },
  { want: 'a wagon escorted to market', tell: 'it rides high for a full load' },
  { want: 'the widow visited before the funeral', tell: 'he has a paper for her to mark' },
  { want: 'a lock opened without the key', tell: 'the key is with a man he will not name' },
  { want: 'the drowned man recovered', tell: 'he knows which bend to look in' },
  { want: 'the fields blessed', tell: 'nothing has grown in the near strip for two seasons' },
  { want: 'the old road found again', tell: 'he asks whether the toll-keeper can see it from his gate' },
  { want: 'a lamp kept burning at the crossing', tell: 'he will not say who it is for, and pays for a month at once' },
];
