// CLIENT MOTIVE POOL v2 — the `hides` field reshaped as an OBSERVABLE TELL.
//
// v1 dealt the client's inner motive ("is paying off a blackmailer"). The model pasted it as an
// explanation — "though the money is to buy off a blackmailer" — in 46% of cards, because a
// psychological truth can only enter prose AS a statement of that truth.
// v2 deals a THING THAT CAN BE SEEN instead. Pasting an observable detail is harmless: it IS the
// card's concrete particular. This is the same principle as the engine's pay glosses being
// "pre-shaped to read whole if pasted" (game.ts:907) — make the field safe to copy rather than
// forbidding the copy.
export interface Motive2 { want: string; tell: string }
export const MOTIVES2: Motive2[] = [
  { want: 'clear the ruin, and be seen paying for it', tell: 'he counts the fee out twice and still gets it wrong' },
  { want: 'get his horse back', tell: 'the saddle is already gone, sold separately' },
  { want: 'carry a chest inland', tell: 'it is roped shut in three places and none of the knots match' },
  { want: 'pen the beasts', tell: 'the brands on them have been cut out' },
  { want: 'find her husband', tell: 'she has already moved his tools out of the shed' },
  { want: 'lead the hunt out at dawn', tell: 'he has told two different men they will lead it' },
  { want: 'bring a bird back alive', tell: 'there is a thread still tied to its leg' },
  { want: 'catch the thief', tell: 'he asks that the thief not be brought through the village' },
  { want: 'fill the pit before the rains', tell: 'the spoil heap beside it is smaller than the hole' },
  { want: 'watch the ridgeline', tell: 'his cart is loaded and standing in the yard' },
  { want: 'bring proof her husband is dead', tell: 'the banns are already read' },
  { want: 'fetch her sister home', tell: 'the sister sent back the money that was sent to her' },
  { want: 'clear the well', tell: 'he will not draw from it himself while you work' },
  { want: 'collect a debt', tell: 'the account he shows you is written in one hand, start to finish' },
  { want: 'return the boy to his apprenticeship', tell: 'the boy left his good boots behind' },
  { want: 'open a grave', tell: 'he brings his own spade and will not lend it' },
  { want: 'put the dogs down', tell: 'they come to him when he calls them' },
  { want: 'deliver a letter upriver', tell: 'the seal on it is fresh but the paper is old' },
  { want: 'watch the ford for a week', tell: 'he asks what time the watch changes' },
  { want: 'drive a stranger off his land', tell: 'the stranger has been there longer than he has' },
  { want: 'explain the fire', tell: 'he was in the next village that night and can name who saw him' },
  { want: 'settle a boundary', tell: 'the stone has been moved recently — the grass under it is still green' },
  { want: 'the crop got in fast', tell: 'two different factors have receipts for it' },
  { want: 'recover an account book', tell: 'he asks for it unopened, and says so twice' },
  { want: 'track the wolf', tell: 'the sheep were killed but not eaten' },
  { want: 'guard the bridge', tell: 'he has already had a toll-board painted' },
  { want: 'the ruin surveyed', tell: 'he knows how many rooms it has' },
  { want: 'stop a rumour', tell: 'he repeats it to you in full, twice, to be sure you have it right' },
  { want: 'find a child', tell: 'he does not know what colour her hair is' },
  { want: 'tend the sick at his own cost', tell: 'he has had their beds moved to the outbuilding already' },
  { want: 'copy a map', tell: 'the original has another man\'s name scratched off the corner' },
  { want: 'move the flock to new pasture', tell: 'the new pasture is on the far side of a border' },
  { want: 'meet a shipment at the landing', tell: 'the manifest is lighter than the cart will be' },
  { want: 'open the cellar', tell: 'the lock is new and the door is old' },
  { want: 'catch a rider before the crossing', tell: 'he cannot say what the rider carries, only that it must not arrive' },
  { want: 'guard the harvest', tell: 'he has hired three separate parties to guard it' },
  { want: 'identify a corpse', tell: 'he brings the dead man\'s ring with him' },
  { want: 'search a room', tell: 'he tells you which board to look under' },
  { want: 'reopen the mine', tell: 'the last crew\'s tools are still down there' },
  { want: 'break a horse to saddle', tell: 'nobody local will bid on it' },
  { want: 'count the granary', tell: 'he asks for the count in writing, and for no copy to be kept' },
  { want: 'vouch a stranger for', tell: 'they arrived on the same day' },
  { want: 'watch the churchyard', tell: 'his own man has the other key' },
  { want: 'fell a tree at the field\'s corner', tell: 'the ground around it is bare where nothing has been planted' },
  { want: 'find a deed', tell: 'he describes the box it is in before you ask' },
  { want: 'stop a fight at the mill', tell: 'both men work for him' },
  { want: 'value the goods honestly', tell: 'the crates are packed in straw from another county' },
  { want: 'drain the marsh', tell: 'he asks for the spoil carted away, not spread' },
  { want: 'ransom a captive', tell: 'the ransom he offers is under what the family already paid' },
  { want: 'return a runaway', tell: 'her wages are still owed and he mentions them first' },
  { want: 'explain the smoke on the ridge', tell: 'he smelled of it when he arrived' },
  { want: 'move a grave before the sale', tell: 'the buyer is waiting in his yard' },
  { want: 'find the hound', tell: 'he asks whether it can be brought back muzzled' },
  { want: 'escort a wagon to market', tell: 'it rides high for a full load' },
  { want: 'the widow visited before the funeral', tell: 'he has a paper for her to mark' },
  { want: 'open a lock without the key', tell: 'the key is with a man he will not name' },
  { want: 'recover the drowned man', tell: 'he knows which bend to look in' },
  { want: 'bless the fields', tell: 'nothing has grown in the near strip for two seasons' },
  { want: 'find the old road again', tell: 'he asks whether the man on the toll gate can see it' },
  { want: 'keep a lamp burning at the crossing', tell: 'he pays for a month at once and gives no name' },

  // ── expansion to production size (designer: pool should be 150+ so a tell recurs about once
  // per 150 draws rather than once per 60)
  { want: 'a boat pulled off the mud', tell: 'the oars are already stowed in his own shed' },
  { want: 'find the pigs', tell: 'he has cleaned the sty out ready' },
  { want: 'talk her son sense into', tell: 'she asks that nobody speak to him alone' },
  { want: 'walk a wall and measured', tell: 'he paces it out for you before you agree' },
  { want: 'pay the miller off', tell: "the sacks in his yard bear the miller's mark" },
  { want: 'mend a cart by market day', tell: 'the axle was cut, not worn through' },
  { want: 'move the strangers on', tell: 'he has fed them every night for a week' },
  { want: 'find a ring in the rushes', tell: 'he describes the inside of the band' },
  { want: 'watch the roof at night', tell: 'there is new thatch on one side only' },
  { want: 'a bull brought back', tell: 'the gate was lifted off its hinges, not broken' },
  { want: 'the reeve spoken to quietly', tell: 'he asks you to go after dark' },
  { want: 'keep a boy out of the mine', tell: "the boy's father is not mentioned once" },
  { want: 'recover her dowry', tell: 'the chest it came in is still in her room' },
  { want: 'guard the orchard', tell: 'the windfalls have been swept up already' },
  { want: 'a wound looked at', tell: 'he keeps his sleeve down while he talks' },
  { want: 'check the dam', tell: 'he asks that it be checked from the far bank only' },
  { want: 'keep a name off a list', tell: 'he has the list with him' },
  { want: 'the ferry run for a week', tell: "the ferryman's dog is at his heel" },
  { want: 'move a hive before winter', tell: 'the bees are already dead' },
  { want: 'measure the corn', tell: 'he brings his own measure' },
  { want: 'shoe a horse quietly', tell: 'there is a brand under the new shoe' },
  { want: 'dig the ditch deeper', tell: 'the old ditch was dug last month' },
  { want: 'watch her brother', tell: 'she pays more than the work is worth' },
  { want: 'keep a fire lit at the ford', tell: 'he asks for it lit at the same hour each night' },
  { want: 'count the barrels', tell: 'two are lighter than the rest and he knows which' },
  { want: 'carry a message and no answer waited for', tell: 'he does not ask what happens after' },
  { want: 'dip the sheep', tell: 'the flock is bigger than his pasture holds' },
  { want: "a stranger's boots returned", tell: 'the boots are the wrong size for the man he names' },
  { want: 'keep the smith busy', tell: 'he pays for a week of work with nothing to make' },
  { want: 'cap a well', tell: 'the rope has been cut off short' },
  { want: 'drain the pond by spring', tell: 'he asks who will be watching while it drains' },
  { want: 'hang a door on a ruin', tell: 'the ruin has no roof' },
  { want: 'find her cat', tell: 'she has already had the yard dug over' },
  { want: 'count the tolls for a day', tell: 'he stands where he cannot see the road' },
  { want: 'carry a coffin at night', tell: 'it is lighter than a man' },
  { want: 'drive the geese to market', tell: 'the market is three days the other way' },
  { want: 'write off a debt', tell: 'the notched stick has been snapped and rejoined' },
  { want: 'watch the road for a rider', tell: 'he has a horse saddled in the yard' },
  { want: "a child's grave tidied", tell: 'there is no name on the stone' },
  { want: 'clear the barn out', tell: 'he will not go inside with you' },
  { want: 'change a lock', tell: 'the old key is on the table between you' },
  { want: 'count the sheep at dusk', tell: 'he asks the count be given to him alone' },
  { want: 'a stranger followed home', tell: 'he already knows which lane' },
  { want: 'break the ice on the pond', tell: 'he asks what floats up' },
  { want: 'witness a will', tell: 'the man who is to sign it is not present' },
  { want: 'lay the hedge before spring', tell: 'it has been laid twice this year' },
  { want: 'carry a lamp to the barrow', tell: 'he stops at the field gate and waits' },
  { want: 'move the horses after dark', tell: 'their hooves have been wrapped' },
  { want: 'watch a stall at market', tell: 'the goods on it are not from here' },
  { want: 'the bell rung at midnight', tell: 'he asks that it be rung only once' },
  { want: 'count a cellar for rats', tell: 'the traps in it are unset' },
  { want: 'keep the crossing clear', tell: 'he asks how long a man could hide under the bridge' },
  { want: "a stranger's horse stabled", tell: 'the saddlebags are gone from it' },
  { want: 'the ford staked out', tell: 'the stakes are already cut and stacked' },
  { want: 'burn a bundle unopened', tell: 'the string on it is his own' },
  { want: 'keep the pigs off the common', tell: 'the common is not his to keep them off' },
  { want: 'walk a man home safe', tell: 'he asks which way you will take him' },
  { want: 'the shutters nailed', tell: 'from the inside' },
  { want: 'a debt read aloud in the square', tell: 'he cannot read it himself' },
  { want: 'mark the calves', tell: 'the marking iron is new' },
  { want: 'carry a body to the church', tell: 'he has already paid the sexton' },
  { want: 'mow the meadow early', tell: 'it is not ready and he knows it' },
  { want: 'move a strongbox', tell: 'he asks that it be moved during the fair' },
  { want: 'search the woodpile', tell: 'he says which end to start' },
  { want: 'burn a letter after reading', tell: 'he watches to see you read it' },
  { want: 'drive the herd at night', tell: 'the drove road runs past a gate he owns' },
  { want: 'mend a hole in a wall', tell: 'the stones from it are stacked neatly nearby' },
  { want: 'question the tanner', tell: 'he owes the tanner nothing, he says twice' },
  { want: 'escort a girl to her wedding', tell: 'she has not been told' },
  { want: 'clear the culvert', tell: 'there is cloth caught in the grating' },
  { want: "a stranger's tools returned", tell: 'the tools have his own mark filed off' },
  { want: 'stop the mill wheel for a day', tell: 'the miller was not asked' },
  { want: 'watch a grave three nights', tell: 'he names the third night first' },
  { want: 'walk the fence line', tell: 'he walks it with you but not to the end' },
  { want: 'weigh a sack', tell: 'the scales are his' },
  { want: 'smoke the bees out', tell: 'he has bought the hives already' },
  { want: 'watch a boat at the landing', tell: 'it has been unloaded once tonight' },
  { want: 'taste the well water', tell: 'he will not drink it in front of you' },
  { want: "a stranger's story taken down", tell: 'he supplies the dates before the man does' },
  { want: 'clear the loft', tell: 'the ladder has been moved away from it' },
  { want: 'keep a hound from the hunt', tell: 'the hound belongs to someone else' },
  { want: 'net the millpond', tell: 'he asks for anything found to be brought to him whole' },
  { want: 'a lantern left on the ridge', tell: 'he asks that it be left unlit' },
  { want: 'watch the causeway at low tide', tell: 'he knows exactly when that is' },
  { want: 'hold a barn door shut', tell: 'from the outside' },
  { want: 'the flock brought down early', tell: 'the high pasture has been burned' },
  { want: 'melt a ring down', tell: 'it is still warm' },
  { want: 'count the rick', tell: 'he built it himself, alone, in one night' },
  { want: 'bury a stranger decently', tell: 'he supplies the shroud' },

  // ── expansion to 400+ (designer 2026-08-25): at 149 pairs the rotation ((k+seed)*17)%len puts the
  // SAME tell on several cards of one 24-card batch, and a repeated tell reads as a formula. That is
  // a pool-size problem, not a prompt problem. Same contract as above: `want` is a VERB PHRASE of
  // work to be done (never a nominalisation — "the roof watched at night" rendered as "You are asked
  // who watched it"), `tell` is ONE thing a person could see on the spot that makes the stated
  // reason impossible, aimed at the asker or at the thing they described. No names, no numbers, no
  // durations, no coinages, no "will not say".
  { want: 'shear the flock early', tell: 'the wool sacks in his barn are already full and sewn' },
  { want: 'milk the herd while he is away', tell: 'the milking stool has been carried into the house' },
  { want: 'geld a colt', tell: 'the colt wears a halter with another mark burned into the strap' },
  { want: 'feed the hounds at night', tell: 'their bowls have been scoured and put away on a high shelf' },
  { want: 'bed the horses down', tell: 'every stall has clean straw in it already' },
  { want: 'muzzle the dog', tell: 'the dog has no teeth left in its head' },
  { want: 'drive the swine into the beech woods', tell: 'the way he points out runs past the boundary stones' },
  { want: 'water the beasts at the stream', tell: 'the trough in his own yard is brimming' },
  { want: 'slaughter the old sow', tell: 'the salting barrel was scrubbed out this morning' },
  { want: 'catch the loose ram', tell: 'the gate it came through was tied back with its own rope' },
  { want: 'pen the goats away from the garden', tell: 'the garden has been trodden flat from the inside' },
  { want: 'rub down a lame mare', tell: 'the mare stands square on all her feet' },
  { want: "trim the ponies' hooves", tell: 'the rasp he hands over is worn smooth on one side' },
  { want: 'carry hay up to the high fold', tell: 'the fold has no beasts in it' },
  { want: 'roll the fleeces up for sale', tell: 'the fleeces have been rolled the wrong way, from the outside in' },
  { want: 'tail the lambs', tell: 'the lambs are grown past the age for it' },
  { want: 'nurse a sick calf', tell: 'its mother has been sold out of the byre' },
  { want: 'lead a bull to the cows', tell: 'the cows were moved out of the near field this morning' },
  { want: 'skin the fallen ox', tell: 'he names the yard the hide goes to before it is off the beast' },
  { want: 'hobble the horses at pasture', tell: 'their shoes have been pulled off' },
  { want: 'plough the top field', tell: 'the field is turned and showing green' },
  { want: 'sow the near strip', tell: 'the seed sack he gives you is half chaff' },
  { want: 'weed the bean rows', tell: 'the rows have been hoed clean' },
  { want: 'reap the barley before it rains', tell: 'the barley is still green at the ear' },
  { want: 'stack the sheaves in the barn', tell: 'the barn floor is swept and marked out in chalk' },
  { want: 'thresh the corn', tell: 'the flails hang where no one standing can reach them' },
  { want: 'winnow the last of the grain', tell: 'the chaff heap is bigger than the crop was' },
  { want: 'glean the stubble', tell: 'the stubble has been raked over' },
  { want: 'carry seed corn to the mill', tell: 'the sacks are sewn shut and none of the stitching matches' },
  { want: 'pick the orchard clean', tell: 'the ladders have all been laid flat in the grass' },
  { want: 'graft the young apples', tell: 'the young trees have been ringed through the bark at the root' },
  { want: 'prune the vines back', tell: 'the cuttings from the last pruning were carted away, not burned' },
  { want: 'dig the last of the roots', tell: 'the clamp beside the field is covered and turfed over' },
  { want: 'turn the hay before dark', tell: 'the swathes have been turned once already today' },
  { want: 'spread muck on the fallow', tell: 'the heap has different straw through it than his byre uses' },
  { want: 'fence the new ground', tell: 'the new ground has a footpath worn across it' },
  { want: 'clear stones off the headland', tell: 'a wall along the far side has been built out of them already' },
  { want: 'burn the stubble', tell: 'he wants to know which way the wind sits before he asks the price' },
  { want: 'cut peat on the moor', tell: 'the stack at his door is cut and dried' },
  { want: 'gather rushes at the pond', tell: 'the pond edge is cut over and the cuttings left to rot' },
  { want: 'caulk a boat', tell: 'the seams are tight and dry' },
  { want: 'row a passenger over after dark', tell: 'he loads the boat before you have agreed' },
  { want: 'bail out the flooded cellar', tell: 'the water in it is clean and standing still' },
  { want: 'raise a net from the weir', tell: 'the weir hatch has been left open' },
  { want: 'pole a raft downriver', tell: 'the raft is lashed with rope that is still stiff and new' },
  { want: 'sound the channel', tell: 'he can name the depth at every bend' },
  { want: 'mend the fish traps', tell: 'they are dry and there is no weed on them' },
  { want: 'haul a boat out for the winter', tell: 'the boat has been holed above the waterline' },
  { want: 'carry water to the drovers', tell: 'a spring runs clean into the pond they are standing at' },
  { want: 'sink a new well', tell: 'the old well is capped with a slab too heavy for one man' },
  { want: 'clear the mill leat', tell: 'the leat is running clean' },
  { want: 'fix the sluice gate', tell: 'the gate is chocked open with a wedge cut to fit' },
  { want: 'fish the deep pool', tell: 'the pool was netted lately and the bank is trodden down' },
  { want: 'gather what washed up on the shingle', tell: 'the shingle above the tide line has been raked over' },
  { want: 'ferry a cart across before dark', tell: 'the ford is low enough to walk' },
  { want: 'drag the river below the mill', tell: 'he starts you downstream of the place he says it happened' },
  { want: 'pack the catch in ice before the cart goes', tell: 'the fish in the baskets have been gutted and salted already' },
  { want: 'stop a leak in the dyke', tell: 'the breach has clean cut sides' },
  { want: 'float timber down to the landing', tell: 'the logs have had their ends sawn off where a mark would sit' },
  { want: 'tar a hull before launching', tell: 'the hull has been tarred over something that still shows through' },
  { want: 'prop the barn wall', tell: 'the crack in it has been filled and painted over' },
  { want: 'rethatch the byre', tell: 'the old thatch has been carted off and burned' },
  { want: 'whitewash the dairy', tell: 'the walls are still wet from a washing' },
  { want: 'lay a new floor in the hall', tell: 'the boards taken up are stacked with their nails pulled straight' },
  { want: 'sweep the chimney', tell: 'the hearth is cold and swept bare' },
  { want: 'unblock the drain', tell: 'the grating has been lifted out and set aside neatly' },
  { want: 'clear snow off the roof', tell: 'the side facing the lane has been swept clear already' },
  { want: 'rebuild the wall by the lane', tell: 'the stones have been squared with a chisel and they were rough before' },
  { want: 'shore up the bridge', tell: 'a loaded cart crosses it while you stand there' },
  { want: 'gravel the track', tell: 'the ruts run from his gate to the road and stop' },
  { want: 'hang a gate at the lane end', tell: 'the postholes are dug wider than the posts' },
  { want: 'set a new door frame', tell: 'the frame he has ready is narrower than the doorway' },
  { want: 'stop the roof leaking over the loft', tell: 'the loft floor is dry and stacked with dry goods' },
  { want: 'bar the shutters on the north side', tell: 'the north side looks onto his own yard' },
  { want: 'sink a post at the crossroads', tell: 'he brings the post already cut and lettered' },
  { want: 'clear the fallen tree off the road', tell: 'the stump face is clean and cut with an axe' },
  { want: 'pave the yard before the fair', tell: 'the fair is held across the water' },
  { want: 'relay the hearthstone', tell: 'the mortar under it is fresh' },
  { want: 'fit a bolt to the inside of a door', tell: 'the door opens outward' },
  { want: 'clear the burnt house', tell: 'the roof timbers fell inward and are stacked outside' },
  { want: 'collect the rent from the far holdings', tell: 'those rents have been receipted already' },
  { want: 'carry coin to the fair', tell: 'the purse is sewn shut and light for its size' },
  { want: 'buy back a pledged plough', tell: 'the plough is standing in his own barn' },
  { want: 'stand surety for a man', tell: 'the name on the paper he shows has been written over another' },
  { want: 'witness a bargain at the stone', tell: 'he brings a paper already marked at the foot' },
  { want: 'value a horse for sale', tell: 'he says what the horse is worth before you have looked at it' },
  { want: 'read a summons out at the door', tell: 'he stands well back from the door as you go up' },
  { want: 'serve notice on a tenant', tell: "the tenant's goods are already piled in the lane" },
  { want: 'carry a purse to a house at night', tell: 'the house he names is dark and shuttered at that hour' },
  { want: 'weigh out silver for a bargain', tell: 'his weights ring differently from the ones on the table' },
  { want: 'hold a bond until the fair', tell: 'the wax on it has been softened and pressed again' },
  { want: 'fetch a scribe to the sickbed', tell: 'the papers on the bed are written and want only a mark' },
  { want: 'carry a complaint to the court', tell: 'he asks that it be handed in when the court is rising' },
  { want: 'pay a fine at the gate', tell: 'the sum he counts out is short and he pushes it over anyway' },
  { want: 'sell a team at the fair', tell: 'the harness has been swapped for plain gear with no mark' },
  { want: 'buy grain from the far barns', tell: 'his own barns are full and shut' },
  { want: 'settle a wager', tell: 'both men named on the paper eat at his table' },
  { want: 'carry rents in a locked box', tell: 'the box has been opened and sealed again in a different wax' },
  { want: 'take a horse in payment of a debt', tell: 'the horse has been clipped short where a brand would sit' },
  { want: 'return a pledge to a widow', tell: 'what he hands over is not what the paper describes' },
  { want: 'look for a missing shepherd', tell: 'his crook is back on its peg by the door' },
  { want: 'bring a daughter home from the town', tell: 'her room has been let to a lodger' },
  { want: 'fetch a midwife to the farm', tell: 'the birthing room is unlit and the bed stripped' },
  { want: 'sit with a dying man through the night', tell: 'the man is sitting up eating when you arrive' },
  { want: 'wash and lay out a body', tell: 'the body has been washed by somebody already' },
  { want: 'carry a child to its grandmother', tell: "the child's bundle is packed and waiting at the door" },
  { want: 'find who set the boat adrift', tell: 'the mooring rope was cut, not untied' },
  { want: 'bring a runaway apprentice back', tell: 'his indenture has been struck through' },
  { want: "carry word to a man's wife", tell: 'he watches the lane behind you while he talks' },
  { want: 'stand godfather at a christening', tell: 'the child can walk to the font unaided' },
  { want: "walk a girl to her aunt's house", tell: 'the aunt is the woman standing behind him' },
  { want: 'look for a man gone from the fields', tell: 'his coat and his dinner are still under the hedge' },
  { want: 'fetch a physician to a sick child', tell: 'the child is out in the yard playing when you come' },
  { want: 'lead a search of the high ground', tell: 'he keeps looking down at the water' },
  { want: 'nurse the fever cases at the almshouse', tell: 'those beds were emptied before you were sent for' },
  { want: 'bring a body down off the moor', tell: 'he knows already how heavy it will be to carry' },
  { want: 'find who has been sleeping in the hayloft', tell: 'the loft ladder has been pulled up from above' },
  { want: "take a man's coat back to his family", tell: 'the coat is dry and the weather has been wet' },
  { want: 'sit up with a corpse until morning', tell: 'the coffin lid is nailed down' },
  { want: 'talk a man down off the roof', tell: 'he brings a cart round to the foot of the wall before you climb' },
  { want: 'keep watch on the barn door', tell: 'nothing is stored in the barn behind it' },
  { want: 'walk the boundary after dark', tell: 'he sends you the long way round from the gate' },
  { want: 'stand at the gate until the bell', tell: 'he sets you where the house cannot be seen from the gate' },
  { want: 'follow a cart to the next parish', tell: 'its wheels are bound about with cloth' },
  { want: 'light the beacon on the hill', tell: 'the wood laid ready on it is green and wet' },
  { want: 'douse the lamps along the wharf', tell: 'the lamps have all been trimmed and filled' },
  { want: 'watch a house from the lane', tell: 'he tells you which window' },
  { want: 'count who comes through the gate at night', tell: 'a second latch has been fitted on the inside' },
  { want: 'listen at a wall', tell: 'the plaster on the far side of it is new' },
  { want: 'keep a room empty until morning', tell: 'the bed in it has been slept in' },
  { want: 'walk a dog along the wall at dusk', tell: 'the dog is his and it balks at the corner' },
  { want: 'hold a lantern at the churchyard wall', tell: 'the gate has been oiled and stands open' },
  { want: 'bring a horse to the crossroads and wait', tell: 'the stirrups are set for a smaller rider' },
  { want: 'sit in the loft and watch the yard', tell: 'the yard has been swept clear of tracks' },
  { want: 'knock at a door and come away again', tell: 'he waits at the corner where that door can see him' },
  { want: 'carry a bundle out past the watch', tell: 'the bundle is warm' },
  { want: 'open the shutters at first light', tell: 'they are nailed from the inside' },
  { want: 'wait at the milestone until the moon is up', tell: 'he asks for the same place again the night following' },
  { want: 'cut a mark into a gatepost', tell: 'the post has one on it already, cut deep and painted over' },
  { want: 'walk the lane and count the dogs that bark', tell: 'every dog along it has been shut in' },
  { want: 'sharpen the scythes', tell: 'the blades are new and unmarked' },
  { want: 'forge a set of hinges', tell: 'the old hinges he brings are sound' },
  { want: 'fit a new haft to an axe', tell: 'the head has been ground away on one edge' },
  { want: 'mend a net', tell: 'it has been cut through in a straight line' },
  { want: 'rope a stack against the wind', tell: 'the rope he hands over has been spliced where it was cut' },
  { want: 'make a coffin to measure', tell: 'he gives you the measure without going to look' },
  { want: 'turn a set of bowls', tell: 'he wants nothing cut into the base of them' },
  { want: 'shoe a mule for the road', tell: 'the shoes it wears now are barely worn' },
  { want: 'cast a bell for the chapel', tell: 'the metal he brings is a bell already, broken up' },
  { want: 'tan a hide quickly', tell: 'the hide is still warm' },
  { want: 'weave cloth to a pattern he brings', tell: 'the pattern is cut from the corner of a larger piece' },
  { want: 'dye a bolt of wool dark', tell: 'the wool is dark already' },
  { want: 'brew ale for a wedding', tell: 'no banns have been read at the chapel' },
  { want: 'bake for a house in mourning', tell: 'the shutters are open and the glasses uncovered' },
  { want: 'cut a key from a wax impression', tell: 'the wax was taken from the inside face of the door' },
  { want: 'grind a blade down', tell: 'a notch in it has been closed up with heat' },
  { want: 'fit a lock to a chest', tell: 'the chest has no bottom in it' },
  { want: 'pack glass for a journey', tell: 'the crate stands packed and sealed' },
  { want: 'sew a shroud', tell: 'the linen he brings has been cut from a sheet still on a bed' },
  { want: 'mend a wheel by dark', tell: 'it has been mended before at the same spoke' },
  { want: 'ring the passing bell', tell: 'the bell has been muffled with cloth already' },
  { want: 'dig a grave outside the wall', tell: 'he asks for it longer than a man' },
  { want: 'carry a coffin the long way to the church', tell: 'the short way goes past his own door' },
  { want: 'stand vigil at a shrine', tell: 'the offerings on it are fresh and untouched' },
  { want: 'fetch the priest out to a farm', tell: 'the farm is within sight of the chapel' },
  { want: 'clear the crypt steps', tell: 'they have been swept and salted' },
  { want: 'set a stone over a grave', tell: 'the ground there has never been broken' },
  { want: 'walk the parish bounds', tell: 'he wants you to go round outside the marked stones' },
  { want: 'bless a new field', tell: 'the field has a hollow in it where the ground has sunk' },
  { want: 'carry candles to a wake', tell: 'the house has no fire lit and nobody sitting in it' },
  { want: 'open a burial for the family', tell: 'the family are all standing at the graveside before you arrive' },
  { want: 'carry an offering to the shrine', tell: 'the box is sealed and heavier at one end' },
  { want: 'keep the churchyard gate shut through the night', tell: 'the wall beside it has been broken down to knee height' },
  { want: 'sing a mass for a dead man', tell: 'a name has been scraped off the board at the church door' },
  { want: 'put a marked stone back where it was found', tell: 'he holds it in his bare hands while he talks' },
  { want: 'fell timber on the ridge', tell: 'the trees up there carry a mark that is not his' },
  { want: 'burn charcoal in the copse', tell: 'there is a burnt ring in the copse already' },
  { want: 'split logs for the winter store', tell: 'the store is full to the roof' },
  { want: 'clear brush along the ride', tell: 'the brush has been cut and dragged into a heap that hides the ditch' },
  { want: 'open a quarry face', tell: 'the fall in front of it was pushed down from above' },
  { want: 'shore a mine gallery', tell: 'the props taken out of it are stacked in his yard' },
  { want: 'carry lamps down the shaft', tell: 'the shaft mouth has been boarded over from the outside' },
  { want: 'sink a trial pit', tell: 'he marks the spot without walking the ground' },
  { want: 'haul stone off the hill', tell: 'the stone is dressed and squared already' },
  { want: 'fire the lime kiln', tell: 'the kiln has been drawn and the lime is bagged' },
  { want: 'cut a ride through the wood', tell: 'the line he gives runs straight at a boundary bank' },
  { want: 'keep the fire in overnight', tell: 'the smoke off that chimney can be seen from the far ridge' },
  { want: 'clear a burnt field', tell: 'the burn stops in a straight line at his hedge' },
  { want: 'cart ash out to the fields', tell: 'there is bone in the ash' },
  { want: 'stack a woodpile against a wall', tell: 'there is a fresh opening in that wall, stopped up with brush' },
  { want: 'walk a bull over to another farm', tell: 'the halter he hands you has been cut and knotted' },
  { want: 'carry a covered bird cage', tell: 'the cover is sewn down over the bars' },
  { want: 'take a cat away and lose it', tell: 'the cat wears a collar with a bell on it' },
  { want: 'drown a litter of pups', tell: 'the bitch has been shut in a shed away from the yard' },
  { want: 'dig out a badger set', tell: 'the set has been stopped up already' },
  { want: 'trap the rats in the granary', tell: 'there are no droppings on the granary floor' },
  { want: 'shoot the crows off the corn', tell: 'the corn is stripped bare in one corner and standing everywhere else' },
  { want: 'net the pigeons in the loft', tell: 'the pigeon holes have been blocked with rag from inside' },
  { want: 'lift a hive of bees after dark', tell: 'the hive comes up light when he tilts it' },
  { want: 'smoke a fox out of the bank', tell: 'the bank has been dug into from the field side' },
  { want: 'clear moles from the meadow', tell: 'the mole heaps run in a straight line' },
  { want: 'pull the pike out of the stew pond', tell: 'the pond has been drained and filled again' },
  { want: 'stop up the dovecote', tell: 'the dovecote stands empty and swept' },
  { want: 'gather herbs from the churchyard', tell: 'he names the plant and the hour and not the sickness' },
  { want: 'dose a horse', tell: 'the feed in its manger has not been touched' },
  { want: 'bleed a sick man', tell: 'the man walks out to the gate to meet you' },
  { want: 'set a broken arm', tell: 'the arm has been strapped and set already, badly' },
  { want: 'carry a sick man to the town', tell: 'a spade has been put in the cart beside him' },
  { want: 'mind a house while its people are away', tell: 'their clothes are gone off the pegs' },
  { want: 'sweep a room out for a guest', tell: 'the room was locked and the key is warm from his hand' },
  { want: 'guide a party over the pass', tell: 'he knows which stone marks the turning' },
  { want: 'carry packs for travellers', tell: 'the packs have been weighed and marked' },
  { want: 'walk ahead of a wagon at night', tell: 'the wagon carries no lamp' },
  { want: 'meet a stranger at the milestone', tell: 'he describes the shoes the man will be wearing' },
  { want: 'turn travellers away from the inn', tell: 'the beds there are made and empty' },
  { want: 'hold a pitch at the fair', tell: 'the pitch he names is behind the row where nothing sells' },
  { want: 'carry a pack over the hill without stopping', tell: 'the pack is sewn shut at both ends' },
  { want: 'sell a horse at a fair far off', tell: 'everyone in his yard knows the horse by sight' },
  { want: 'lead a mule train by the old track', tell: 'the old track goes nowhere near the place he names' },
  { want: 'change horses at the halfway house', tell: 'the horse he puts you on came in lame' },
  { want: 'ride ahead and take a room', tell: 'the name he tells you to give is not his own' },
  { want: 'carry a chest to the coast', tell: 'it was packed open in front of you and closed while you watched' },
  { want: 'escort a woman to the boat', tell: 'she has no baggage with her' },
  { want: 'travel with a man and see him aboard', tell: 'the man watches the road behind him, not the water' },
  { want: 'buy passage for a family', tell: 'the passage he pays for does not include a return' },
  { want: 'fetch a horse left at an inn', tell: 'the inn is keeping the saddle and he leaves it there' },
  { want: 'walk a road and mark the fords', tell: 'the fords are marked already on the paper he shows you' },
  { want: 'carry a bag and hand it over unopened', tell: 'the bag has been opened and tied again with new cord' },
  { want: 'meet the goods cart at the crossing', tell: 'that cart came through at dawn and is long gone' },
  { want: 'see a man out of the parish', tell: "the man's cart is loaded and pointed the other way" },
  { want: 'count the hives before winter', tell: 'more stands are set out than there are hives to fill them' },
  { want: 'stand at a door and turn people away', tell: 'the door is locked and the key is in his pocket' },
  { want: 'clear a path to the ice house', tell: 'the ice house door stands open and the sill is wet' },
  { want: 'fill a cart with sand from the pit', tell: 'the pit has been dug out in one place, straight down' },
  { want: 'wash the wool at the stream', tell: 'the stream below the washing place runs clear' },
  { want: 'sort the good apples from the bad', tell: 'the bad have been picked out and taken away' },
  { want: 'carry a barrel down to the cellar', tell: 'it sounds part empty when it is rolled' },
  { want: 'broach a cask at the harvest supper', tell: 'the cask has been broached and stopped again' },
  { want: 'measure a room for a new floor', tell: 'he steps it out ahead of you and gets it right' },
  { want: 'knock a doorway through a wall', tell: 'there is an old doorway in that wall, blocked and plastered' },
  { want: 'clear an attic of its old furniture', tell: 'the locks have been taken off every piece' },
  { want: 'bring a mirror down from the house', tell: 'the mirror is wrapped in cloth and corded already' },
  { want: 'take a bed apart and carry it', tell: 'the bed is stripped and the ropes are cut' },
  { want: 'tidy a workshop', tell: 'the bench has been cleared off and wiped down' },
  { want: 'count the fleeces in the store', tell: 'a count is chalked on the store door' },
  { want: 'take a shutter off a window', tell: 'the window behind it has been bricked up' },
  { want: 'dig over a garden bed', tell: 'the ground there was turned lately and nothing put in it' },
  { want: 'fetch water from the far spring', tell: 'the pump in his yard runs sweet' },
  { want: 'splice a bell rope', tell: 'the bell above it has been taken down' },
  { want: 'carry a lamp down a stairway', tell: 'there are fresh scuffs going down the steps and none coming up' },
  { want: 'oil the chains at the pound', tell: 'the pound stands open and empty' },
  { want: "hang a man's coat back on his peg", tell: 'the peg has been taken off the wall' },
  { want: 'close up a shop for its owner', tell: 'the shelves have been cleared from the back forward' },
  { want: 'fetch a book from a house', tell: 'he describes the shelf and the colour of the binding' },
  { want: 'read a letter aloud to a woman', tell: 'she has the letter and it is unfolded and creased soft' },
  { want: 'write a letter for a man who cannot', tell: "he brings the words on a scrap in somebody else's hand" },
  { want: "carry a dying man's word to his son", tell: 'the son has been in the next room the whole while' },
  { want: 'clear a spring of leaves', tell: 'the leaves in it come from no tree standing near' },
  { want: 'cut turf for a roof', tell: 'there is new turf on the far pitch of that roof already' },
  { want: 'mark trees for felling', tell: 'the trees are marked and he wants the marks moved' },
];
